# Generated by Django 5.0.6 on 2024-05-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_actor_options_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=200, verbose_name='Жанр'),
        ),
    ]
