# Generated by Django 5.0.6 on 2024-05-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_rating',
            field=models.CharField(max_length=10, null=True, verbose_name='Возрастное ограничение'),
        ),
    ]
