# Generated by Django 5.0.6 on 2024-05-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_age_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorited_by', to='movie.movie', verbose_name='Избранные фильмы'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='purchased_movies',
            field=models.ManyToManyField(blank=True, null=True, related_name='purchased_by', to='movie.movie', verbose_name='Купленные фильмы'),
        ),
    ]
